title: TTNRT Status

buildFuture: true
languageCode: en
defaultContentLanguage: en
baseURL: https://status.ttnrtsite.me
enableGitInfo: true

params:
  categories:
    - name: Midwest
      description: The main servers are located here.
      closed: false
    - name: East coast
      description: The main servers are located here.
      closed: false
    - name: Cloudflare
      description: Sites hosted on Cloudflare's servers
      closed: false

  systems:
    - name: CDN
      description: Content delivey network
      category: East coast
      link: https://cdn.ttnrtsite.me
    - name: TTGit
      description: Git source control site
      category: East coast
      link: https://git.ttnrtsite.me
    - name: TTPages
      description: Static websites served from TTGit
      category: Midwest
      link: https://ttnrtsite.io
    - name: API
      description: Access the TTNRT API
      category: Midwest
      link: https://api.ttnrtsite.me
    - name: TTRadio
      description: Listen to music on Discord
      category: Midwest
    - name: Website
      description: Our main website for everything
      category: Cloudflare
      link: https://ttnrtsite.me

  dateFormat: January 2, 2006 at 3:04 PM UTC
  shortDateFormat: 15:04 UTC — Jan 2
  useRelativeTime: true
  skipSeconds: false
  enableLastMod: true
  useLargeHeaderDesign: false
  incidentHistoryFormat: "yearly"
  disableIncidentHistory: false
  disableDarkMode: false
  description: Get service outages here!
  disableComplexCalculations: false
  incidentPostsPerPage: 10
  brand: "#0a0c0f"
  ok: "#008000"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"
  alwaysKeepBrandColor: true
  headerTextColor: white
  googleAnalytics: UA-00000000-1

theme: customtheme

preserveTaxonomyNames: true

taxonomies:
  affected: affected

outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
  term:
    - html
    - json
    - rss
