title: TTNRT Status

buildFuture: true
languageCode: en
defaultContentLanguage: en
baseURL: https://status.ttnrtsite.me
enableGitInfo: true

params:
  categories:
    - name: Midwest
      description: The main servers are located here.
      closed: true

  systems:
    - name: Website
      description: The default website for everything
      category: Midwest
    - name: CDN
      description: Content delivey network
      category: Midwest
    - name: TTGit
      description: Git source control
      category: Midwest
    - name: Assist AI
      description: Our AI assistant
      category: Midwest
    - name: TTPages
      description: Static websites served from TTGit
      category: Midwest
    - name: API
      description: Access the TTNRT API
      category: Midwest
    - name: TTRadio
      description: Listen to music on Discord
      category: Midwest

  dateFormat: January 2, 2006 at 3:04 PM UTC
  shortDateFormat: 15:04 UTC — Jan 2
  useRelativeTime: true
  skipSeconds: false
  enableLastMod: true
  useLargeHeaderDesign: false
  incidentHistoryFormat: "yearly"
  disableIncidentHistory: false
  disableDarkMode: false
  description: Get service outages here!
  disableComplexCalculations: false
  incidentPostsPerPage: 10
  brand: "#0a0c0f"
  ok: "#008000"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"
  alwaysKeepBrandColor: true
  headerTextColor: white
  googleAnalytics: UA-00000000-1

theme: customtheme

preserveTaxonomyNames: true

taxonomies:
  affected: affected

outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg

outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
